In [1]:
# question 1
# Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
arr = np.array([int(x==4) for x in range(10)])
print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [2]:
# question 3
# Create a 3x3 matrix with values ranging from 0 to 8.

import numpy as np
arr =  np.arange(0, 9)
arr = arr.reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# question 2
# Create a vector with values ranging from 10 to 49.

import numpy as np
arr = np.arange(10, 50)
print("The vector: ")
print(arr[1:-1])

The vector: 
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [4]:
# question 4
# Find indices of non-zero elements from [1,2,0,0,4,0].

import numpy as np
arr = np.array([1,2,0,0,4,0])
print("All the index numbers of value 0: ", np.where(arr == 0)[0])

All the index numbers of value 0:  [2 3 5]


In [6]:
# question 5
# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
arr = np.random.random((10,10))
print("The Array:")
xmin, xmax = arr.min(), arr.max()
print(f'The minimum value is: {xmin}, The maximum value is: {xmax}')

The Array:
The minimum value is: 0.0174884387725891, The maximum value is: 0.9992242308046086


In [7]:
# question 6
# Create a random vector of size 30 and find the mean value.

import numpy as np
arr = np.random.random(30)

print(f'{arr}\nThe mean for the array is: {np.mean(arr)}')

[0.89738224 0.69800386 0.94993408 0.31472401 0.73903249 0.94567287
 0.88712585 0.83277893 0.27915324 0.77407847 0.96117495 0.52997854
 0.03243754 0.39432157 0.62135747 0.6870652  0.61517193 0.64404755
 0.78536395 0.49995425 0.60294478 0.10554356 0.17706326 0.39370542
 0.12812707 0.36694625 0.19437084 0.33102702 0.75496334 0.49810048]
The mean for the array is: 0.5547183667600244
